# Generated by Django 4.1.3 on 2022-11-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='post',
        ),
    ]
